"""empty message

Revision ID: 653bc182612c
Revises: 
Create Date: 2024-11-27 19:31:11.449899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653bc182612c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('website', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_title'), ['title'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_title'), ['title'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ppsn', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('salary', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_ppsn'), ['ppsn'], unique=True)

    op.create_table('employee_project',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_project')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_ppsn'))
        batch_op.drop_index(batch_op.f('ix_employee_name'))
        batch_op.drop_index(batch_op.f('ix_employee_email'))
        batch_op.drop_index(batch_op.f('ix_employee_department_id'))

    op.drop_table('employee')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_address'))

    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_title'))

    op.drop_table('project')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_title'))

    op.drop_table('department')
    # ### end Alembic commands ###
