"""empty message

Revision ID: 92e47b498da8
Revises: 653bc182612c
Create Date: 2024-11-29 10:24:57.019123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e47b498da8'
down_revision = '653bc182612c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
